# Generated by Django 5.0.4 on 2024-05-04 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('total_order', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('finished', 'Finished'), ('open', 'Open')], default='open', max_length=10)),
                ('payment_method', models.CharField(blank=True, choices=[('pix', 'PIX'), ('cash', 'Dinheiro'), ('debit', 'Débito'), ('credit', 'Crédito')], default='pix', max_length=10, null=True)),
                ('payied_at', models.DateTimeField(blank=True, null=True, verbose_name='Payment Date and Time')),
            ],
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField()),
                ('customizations', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Order Detail',
                'verbose_name_plural': 'Order Details',
            },
        ),
    ]
