# Generated by Django 5.0.4 on 2024-05-04 21:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('menu_items', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('available_quantity', models.PositiveIntegerField()),
                ('menu_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='menu_items.menuitem')),
            ],
        ),
    ]
